apiVersion: v1
kind: Service
metadata:
  name: echo-box
  labels:
    app: echo-box
spec:
  type: NodePort
  selector:
    app: echo-box
  ports:
  - name: http
    port: 8080
    protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: echo-box
  labels:
    app: echo-box
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: echo-box
    spec:
      containers:
      - name: echo-box
        image: gcr.io/google_containers/echoserver:1.4
        ports:
        - containerPort: 8080
          protocol: TCP
        imagePullPolicy: IfNotPresent
      restartPolicy: Always

