resources:
  title: Resources
  icon: info
  external:
  - name: Community
    url: https://w3-connections.ibm.com/communities/service/html/communityoverview?communityUuid=902efee5-3b0e-4cc3-890f-5b4ba4192f58
  - name: Blog
    url: www.yahoo.com
  - name: Brand
    url: www.yahoo.com
  - name: Design Pattern & Asset Library
    url: www.yahoo.com
  pages:
  - /support/glossary/
  - /support/onboarding/
  - /tools/index/
about:
  title: About The Playbook
  icon: info
  pages:
  - /about/index/
  - /about/nav/
  - /about/faq/
